backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow
media_folder: public/assets/images
public_folder: /assets/images

collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - name: 'global'
        label: 'Global'
        file: 'public/data/pages/global.json'
        fields:
          - {label: 'Title', name: 'title', widget: 'string'}
          - {label: 'Copyright', name: 'copyright', widget: 'markdown'}
